<?php

use Src\Core\Env;

return [
    'app_name' => Env::get('APP_NAME', 'PHP File Manager'),
    'base_url' => Env::get('APP_URL', 'http://localhost:8000'),
    'timezone' => Env::get('APP_TIMEZONE', 'Asia/Ho_Chi_Minh'),
    'session' => [
        'lifetime_minutes' => max(1, (int) Env::get('SESSION_LIFETIME_MINUTES', 120)),
        'remember_me_days' => max(1, (int) Env::get('REMEMBER_ME_DAYS', 30)),
    ],
    'db' => [
        'host' => Env::get('DB_HOST', '127.0.0.1'),
        'port' => Env::get('DB_PORT', '3306'),
        'database' => Env::get('DB_DATABASE', 'php_file_manager'),
        'username' => Env::get('DB_USERNAME', 'root'),
        'password' => Env::get('DB_PASSWORD', ''),
        'charset' => Env::get('DB_CHARSET', 'utf8mb4'),
    ],
    'mail' => [
        'host' => Env::get('MAIL_HOST', ''),
        'port' => (int) Env::get('MAIL_PORT', 587),
        'username' => Env::get('MAIL_USERNAME', ''),
        'password' => Env::get('MAIL_PASSWORD', ''),
        'encryption' => Env::get('MAIL_ENCRYPTION', 'tls'),
        'from_email' => Env::get('MAIL_FROM_EMAIL', 'no-reply@example.com'),
        'from_name' => Env::get('MAIL_FROM_NAME', 'PHP File Manager'),
        'password_reset_minutes' => (int) Env::get('PASSWORD_RESET_MINUTES', 30),
    ],
    'upload' => [
        'dir' => dirname(__DIR__) . '/storage/uploads',
        'thumbnail_dir' => dirname(__DIR__) . '/storage/thumbnails',
        'temp_dir' => dirname(__DIR__) . '/storage/temp',
        'blocked_extensions' => [
            'php', 'phtml', 'phar', 'cgi', 'pl', 'py', 'rb', 'sh', 'bash',
            'bat', 'cmd', 'ps1', 'exe', 'dll', 'com', 'scr', 'msi',
            'js', 'mjs', 'html', 'htm', 'svg', 'htaccess',
        ],
        'max_size' => (int) Env::get('UPLOAD_MAX_SIZE_MB', 10) * 1024 * 1024,
        'max_files_per_upload' => (int) Env::get('UPLOAD_MAX_FILES_PER_UPLOAD', 10),
        'default_user_storage_limit' => (int) Env::get('DEFAULT_USER_STORAGE_LIMIT_MB', 500) * 1024 * 1024,
        'reserved_free_space' => (int) Env::get('STORAGE_RESERVED_FREE_MB', 1024) * 1024 * 1024,
        'trash_retention_days' => (int) Env::get('TRASH_RETENTION_DAYS', 7),
        'allowed_mimes' => [
            'image/jpeg' => ['extension' => 'jpg', 'type' => 'image'],
            'image/png' => ['extension' => 'png', 'type' => 'image'],
            'image/gif' => ['extension' => 'gif', 'type' => 'image'],
            'image/webp' => ['extension' => 'webp', 'type' => 'image'],
            'image/avif' => ['extension' => 'avif', 'type' => 'image'],
            'image/bmp' => ['extension' => 'bmp', 'type' => 'image'],
            'image/x-ms-bmp' => ['extension' => 'bmp', 'type' => 'image'],
            'application/pdf' => ['extension' => 'pdf', 'type' => 'document'],
            'text/plain' => ['extension' => 'txt', 'type' => 'document'],
            'text/csv' => ['extension' => 'csv', 'type' => 'spreadsheet'],
            'application/csv' => ['extension' => 'csv', 'type' => 'spreadsheet'],
            'application/vnd.ms-excel' => ['extension' => 'xls', 'type' => 'spreadsheet'],
            'text/markdown' => ['extension' => 'md', 'type' => 'document'],
            'application/json' => ['extension' => 'json', 'type' => 'document'],
            'application/xml' => ['extension' => 'xml', 'type' => 'document'],
            'text/xml' => ['extension' => 'xml', 'type' => 'document'],
            'application/yaml' => ['extension' => 'yaml', 'type' => 'document'],
            'application/x-yaml' => ['extension' => 'yaml', 'type' => 'document'],
            'text/yaml' => ['extension' => 'yaml', 'type' => 'document'],
            'application/rtf' => ['extension' => 'rtf', 'type' => 'document'],
            'text/rtf' => ['extension' => 'rtf', 'type' => 'document'],
            'application/zip' => ['extension' => 'zip', 'type' => 'archive'],
            'application/x-zip-compressed' => ['extension' => 'zip', 'type' => 'archive'],
            'multipart/x-zip' => ['extension' => 'zip', 'type' => 'archive'],
            'application/x-7z-compressed' => ['extension' => '7z', 'type' => 'archive'],
            'application/vnd.rar' => ['extension' => 'rar', 'type' => 'archive'],
            'application/x-rar-compressed' => ['extension' => 'rar', 'type' => 'archive'],
            'application/gzip' => ['extension' => 'gz', 'type' => 'archive'],
            'application/x-gzip' => ['extension' => 'gz', 'type' => 'archive'],
            'application/x-tar' => ['extension' => 'tar', 'type' => 'archive'],
            'application/msword' => ['extension' => 'doc', 'type' => 'document'],
            'application/x-ole-storage' => ['extension' => 'doc', 'type' => 'document'],
            'application/vnd.ms-office' => ['extension' => 'doc', 'type' => 'document'],
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => ['extension' => 'docx', 'type' => 'document'],
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' => ['extension' => 'xlsx', 'type' => 'spreadsheet'],
            'application/vnd.ms-powerpoint' => ['extension' => 'ppt', 'type' => 'presentation'],
            'application/vnd.openxmlformats-officedocument.presentationml.presentation' => ['extension' => 'pptx', 'type' => 'presentation'],
            'application/vnd.oasis.opendocument.text' => ['extension' => 'odt', 'type' => 'document'],
            'application/vnd.oasis.opendocument.spreadsheet' => ['extension' => 'ods', 'type' => 'spreadsheet'],
            'application/vnd.oasis.opendocument.presentation' => ['extension' => 'odp', 'type' => 'presentation'],
            'audio/mpeg' => ['extension' => 'mp3', 'type' => 'audio'],
            'audio/mp3' => ['extension' => 'mp3', 'type' => 'audio'],
            'audio/wav' => ['extension' => 'wav', 'type' => 'audio'],
            'audio/x-wav' => ['extension' => 'wav', 'type' => 'audio'],
            'audio/ogg' => ['extension' => 'ogg', 'type' => 'audio'],
            'video/mp4' => ['extension' => 'mp4', 'type' => 'video'],
            'video/webm' => ['extension' => 'webm', 'type' => 'video'],
            'video/quicktime' => ['extension' => 'mov', 'type' => 'video'],
            'font/ttf' => ['extension' => 'ttf', 'type' => 'font'],
            'application/x-font-ttf' => ['extension' => 'ttf', 'type' => 'font'],
            'application/font-sfnt' => ['extension' => 'ttf', 'type' => 'font'],
            'font/otf' => ['extension' => 'otf', 'type' => 'font'],
            'application/x-font-otf' => ['extension' => 'otf', 'type' => 'font'],
            'application/vnd.ms-opentype' => ['extension' => 'otf', 'type' => 'font'],
            'font/woff' => ['extension' => 'woff', 'type' => 'font'],
            'application/font-woff' => ['extension' => 'woff', 'type' => 'font'],
            'application/x-font-woff' => ['extension' => 'woff', 'type' => 'font'],
            'font/woff2' => ['extension' => 'woff2', 'type' => 'font'],
            'application/font-woff2' => ['extension' => 'woff2', 'type' => 'font'],
        ],
    ],
    'onlyoffice' => [
        'document_server_url' => Env::get('ONLYOFFICE_DOCUMENT_SERVER_URL', ''),
        'jwt_secret' => Env::get('ONLYOFFICE_JWT_SECRET', ''),
        'file_token_secret' => Env::get('ONLYOFFICE_FILE_TOKEN_SECRET', Env::get('APP_NAME', 'PHP File Manager')),
        'token_ttl' => (int) Env::get('ONLYOFFICE_FILE_TOKEN_TTL', 900),
    ],
];
